### PR TITLE
add basic Debian packaging

### PR DESCRIPTION
**Pull request by zabbal**
The resulted packages are not perfect but it's start. Feel free to improve :)

### CODE REVIEW

**Comment by guruofquality** [comment]
There is also this branch https://github.com/fairwaves/UHD-Fairwaves/tree/debian maybe we should compare notes.

**Comment by zabbal** [comment]
Doh, did not double-checked before making pull-request - the debian branch certainly looks better, please merge it into master to avoid further confusion.

**Comment by guruofquality** [comment]
@zabbal sorry about that, I was actually thinking about merging the branch earlier that day too. You also asked about ppa for recent uhd, take a look at https://launchpad.net/~gqrx/+archive/ubuntu/snapshots

**Comment by zabbal** [comment]
I thought it's better to use https://launchpad.net/~guruofquality/+archive/ubuntu/pothos/+packages?field.name_filter=&field.status_filter=published&field.series_filter=vivid :)

**Comment by guruofquality** [comment]
@zabbal -- I didn't want to shamelessly self promote :-) Also, gqrx snapshots ppa is impressive. It would be neat to combine the efforts for hardware support. Anyway the immediate plan is to dput some umtrx debs onto my ppa repository, hopefully this week.

**Comment by guruofquality** [comment]
@zabbal just FYI an umtrx 1.0.3 package is available for on my ppa

**Pull request closed without merging**
